//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.13 at 10:35:07 AM CST 
//


package com.rich.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pokemon complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pokemon">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="abilities" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="baseExperience" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="heldItems" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="locationAreaEncounters" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pokemon", propOrder = {
    "id",
    "abilities",
    "baseExperience",
    "heldItems",
    "locationAreaEncounters"
})
public class Pokemon {

    @XmlElement(required = true)
    protected BigInteger id;
    @XmlElement(required = true)
    protected String abilities;
    @XmlElement(required = true)
    protected BigInteger baseExperience;
    @XmlElement(required = true)
    protected String heldItems;
    @XmlElement(required = true)
    protected String locationAreaEncounters;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the abilities property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbilities() {
        return abilities;
    }

    /**
     * Sets the value of the abilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbilities(String value) {
        this.abilities = value;
    }

    /**
     * Gets the value of the baseExperience property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBaseExperience() {
        return baseExperience;
    }

    /**
     * Sets the value of the baseExperience property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBaseExperience(BigInteger value) {
        this.baseExperience = value;
    }

    /**
     * Gets the value of the heldItems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeldItems() {
        return heldItems;
    }

    /**
     * Sets the value of the heldItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeldItems(String value) {
        this.heldItems = value;
    }

    /**
     * Gets the value of the locationAreaEncounters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationAreaEncounters() {
        return locationAreaEncounters;
    }

    /**
     * Sets the value of the locationAreaEncounters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationAreaEncounters(String value) {
        this.locationAreaEncounters = value;
    }

}
