//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.13 at 10:35:07 AM CST 
//


package com.rich.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for props.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="props">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="all"/>
 *     &lt;enumeration value="id"/>
 *     &lt;enumeration value="abilities"/>
 *     &lt;enumeration value="baseExperience"/>
 *     &lt;enumeration value="heldItems"/>
 *     &lt;enumeration value="locationAreaEncounters"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "props")
@XmlEnum
public enum Props {

    @XmlEnumValue("all")
    ALL("all"),
    @XmlEnumValue("id")
    ID("id"),
    @XmlEnumValue("abilities")
    ABILITIES("abilities"),
    @XmlEnumValue("baseExperience")
    BASE_EXPERIENCE("baseExperience"),
    @XmlEnumValue("heldItems")
    HELD_ITEMS("heldItems"),
    @XmlEnumValue("locationAreaEncounters")
    LOCATION_AREA_ENCOUNTERS("locationAreaEncounters");
    private final String value;

    Props(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Props fromValue(String v) {
        for (Props c: Props.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
